### ISSUE TITLE
Submission 1 Review

### ISSUE THREAD

**Issue by SWHarrison** [Perzival1312/cs13#2]
Bases.py works as expected. If you can avoid using the ```**``` operator or the ```pow``` function it can make it slightly more efficient.

You can incrementally increase what you multiply the base by setting a value to multiply each number by, starting at 1, then multiplying the current multiplier by the base after each digit. So the first iteration is base^0, then base^1, then base^2, and so on, without repeated calculation.

Recursive binary search is not working, as there is no base case for when the item is not found. One possibility is considering what happens when the range of items is 0 or 1, and what to do then.

**Comment by Perzival1312** [comment]
its fixed...
